version: 2
sources:
   - name: raw
     schema : gz_raw_data
     
     tables: 
       - name: sales
         identifier : raw_gz_sales
         description : sales of Greenweez
         columns:
           - name: date_date
             description: date d'achat
           - name: orders_id 
             description: id de commande
           - name: products_id
             description: id des produits
           - name: revenue
             description: chiffre d'affaires
           - name: quantity
             description: quantité de produits vendus par commande
         tests:
            - unique:
                column_name: "(orders_id || '-' || pdt_id)"
          
       - name: product
         identifier : raw_gz_product
         description: produits de Greenweez
         columns:
           - name: products_id
             description: primary_key
             tests:
               - unique
               - not_null
           
       - name: ship
         identifier : raw_gz_ship
         description: couts logistiques
         columns:
           - name: orders_id
             description: primary_key
             tests:
               - unique
               - not_null
        